### ISSUE TITLE
Avoid POSTGRES_USER and POSTGRES_PASSWORD duplication in docker-compose.yml

### ISSUE THREAD

**Issue by riggraz** [astuto/astuto#167]
Right now these two environment variables are duplicated in `docker-compose.yml`, i.e. they must be inserted for both `app` and `db` services. This is inconvenient because the user need to type them twice, so there's the possibility that they mistypes them.

**Comment by GabrielRozendo** [comment]
an idea would be specify a section to reuse in containers...
minimal example based on official docker-compose.yml
(need to investigate if works as should be)

```yaml
version: '3.4'
x-environment:
  &default-environment
  POSTGRES_USER: astuto
  POSTGRES_PASSWORD: dbpass
  BASE_URL: http://localhost:3000
  SECRET_KEY_BASE: secretkeybasehere

services:
  db:
    image: postgres:14.5
    environment: *default-environment
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      environment: *default-environment
    ports:
      - "3000:3000"
    depends_on:
      - db
```
