### ISSUE TITLE
Allow for self-signed certs and custom CAs via config flag and compose examples

### ISSUE THREAD

**Issue by byjrack** [astuto/astuto#203]
_Assumed in the future the Compose will support TLS termination_

As part of very initial testing I was using a self-signed cert with nginx and was getting failure in the OAuth callback.  The issue is in https://github.com/astuto/astuto/blob/main/app/workflows/OAuthExchangeAuthCodeForProfile.rb#L36 as that call will fail if TLS is broken (eg self-signed or unknown CA).

Quick fix was to add 
`HTTParty::Basement.default_options.update(verify: false)` to ExchangeCode workflow as a live patch (or custom image), but this is far from ideal.  As an example with TLS termination is looked at having these type of flags available in the env file will be super handy.  

- public key file
- private key file
- custom CA
- disable TLS

Had the most success with nginx, but I am sure haproxy or even pound could be adapted for the same basic parameters.  Poking at the same on my own machine, but figured I would at least get it on the radar for any termination feature work.

**Comment by byjrack** [comment]
And for anyone needing the TLS type support you can add the following to compose.  Definite opportunity to optimize, but at least gets you going.  And I renamed the service "web" to "app" just to help myself, but you can tweak it as you need.  Adding a custom CA is a bit tougher given the need to rehash, but if you control entrypoint you can do it there or post-compose via exec.

docker-compose.yml
```
  https:
    image: nginx
    links:
      - app
    volumes:
      - ./cert.key:/root/ssl/cert.key:ro
      - ./cert.crt:/root/ssl/cert.crt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
```

default.conf
```
server {
    listen                  443 ssl default_server;
    server_name             astuto.example.com;
    ssl_certificate         /root/ssl/cert.crt;
    ssl_certificate_key     /root/ssl/cert.key;
    ssl_session_tickets on;

    location / {
        proxy_pass "http://app:3000/";
        proxy_set_header Host $host;
        proxy_set_header origin 'http://astuto.example.com';
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }
    error_page   500 502 503 504  /50x.html;
}

server {
   listen 80;
   server_name _;
   return 301 https://$host$request_uri;
}
```
