### ISSUE TITLE
SMTP Relay Sendgrid not working

### ISSUE THREAD

**Issue by TheGeeKing** [astuto/astuto#317]
Hi,

I tried to use Sendgrid to relay emails but I cannot make it work. I have set up the required env with sendgrid provided info but I don't receive anything. I tried a test email from sendgrid website and I get the email from my domain name as expected and I already used sendgrid in the past in another project and it worked.

```
environment:
  EMAIL_SMTP_HOST: smtp.sendgrid.net
  EMAIL_SMTP_USER: apikey
  EMAIL_SMTP_PASS: TOKEN
```
