### ISSUE TITLE
SMTP configuration

### ISSUE THREAD

**Issue by mihha** [astuto/astuto#330]
Guys, I am trying to configure docker installation to send emails, but something is not working, and I can't see any messages in any log to see what exactly is wrong

I have this in my docker file
```
  web:
    image: riggraz/astuto:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MY_PASSWORD
      BASE_URL: https://my_url.com
      SECRET_KEY_BASE: MY_SECRET_KEY
      EMAIL_DELIVERY_METHOD: smtp
      EMAIL_SMTP_HOST: "my_amazon_smtp_host_address"
      EMAIL_SMTP_PORT: 465
      EMAIL_SMTP_USER: "my_ses_username"
      EMAIL_SMTP_PASS: "my_ses_username_password"
      EMAIL_SMTP_AUTH: true
      EMAIL_SMTP_TLS: true
      EMAIL_MAIL_FROM: "reply@domain.com"
      EMAIL_MAIL_REPLY_TO: "reply@domain.com"
```

SMTP server credentials, port and everything else is for sure correct, because I have checked this with my other self-hosted service

I have no idea how to debug this

Can someone point me into the right direction, please?

**Comment by inthebrilliantblue** [comment]
Im pretty sure astuto is just broken when it comes to email. As far as I can tell, it has no proper logging for when someone provides incorrect SMTP user / pass to it, as it still gives me logs that it sent a confirmation email successfully even though I intentionally gave it wrong credentials to try to force the logs to change. And based on this tickets age with no replies, it doesnt give me the warm fuzzies about a fix.

**Comment by mihha** [comment]
I agree to your comment about the fix. Already gave up on Astuto two weeks ago

Too bad, because this looked promising, but I had to move on and use something else

**Comment by pilasguru** [comment]
Astuto has mail option broken. 

I have configured a local (docker) smtp proxy without validation requirements and this is the log each time astuto try to send an e-mail:

```
2024-05-31T19:31:35.886096+00:00 a64adacb47b7 postfix/smtpd[139]: connect from astuto-web-1.astuto_astuto[172.27.0.4]
2024-05-31T19:31:35.888266+00:00 a64adacb47b7 postfix/smtpd[139]: lost connection after AUTH from astuto-web-1.astuto_astuto[172.27.0.4]
2024-05-31T19:31:35.888420+00:00 a64adacb47b7 postfix/smtpd[139]: disconnect from astuto-web-1.astuto_astuto[172.27.0.4] ehlo=1 auth=0/1 commands=1/2
```

Astuto is not completing the SMTP process.

```
Current version: 20240521124018
```

**Comment by pilasguru** [comment]
Refer to #317 #364

**Comment by riggraz** [comment]
Hi everyone, I've finally had the time to dig into the problem. I pushed a new commit to main that should fix the problem, or at least give more information about it.

First of all, I added an environment variable `EMAIL_RAISE_DELIVERY_ERRORS` that will log smtp errors. I suggest setting `EMAIL_RAISE_DELIVERY_ERRORS` to true when testing the smtp configuration. After checking that it works, I suggest setting it back to false. Note: if you're running astuto in production, you'll have to check the .log files instead in the log/ folder (or set `RAILS_LOG_TO_STDOUT` to true to log to stdout).

I was also able to make Astuto smtp work both locally (without SSL and authentication) and in production (using [Brevo](https://www.brevo.com/) smtp, SSL, authentication needed). Let's see both configurations.

**Local configuration (development)**

I have setup a simple SMTP server ([MailCatcher](https://mailcatcher.me/) on localhost, port 1025, no authentication required, no SSL). I have set the following environment variables in `docker-compose.yml` in `web` container:

```
EMAIL_DELIVERY_METHOD: smtp
EMAIL_RAISE_DELIVERY_ERRORS: true
EMAIL_SMTP_HOST: host.docker.internal
EMAIL_SMTP_PORT: 1025
EMAIL_SMTP_USER: ""
EMAIL_SMTP_PASS: ""
```

(`host.docker.internal` is used to refer to the host machine inside the docker container)
(user and pass are required, but left blank because smtp server required no authentication)

**Production configuration**

```
EMAIL_DELIVERY_METHOD=smtp
EMAIL_RAISE_DELIVERY_ERRORS: true
EMAIL_SMTP_HOST=smtp-relay.brevo.com
EMAIL_SMTP_PORT=<not-shown>
EMAIL_SMTP_USER=<not-shown>
EMAIL_SMTP_PASS=<not-shown>
```

Both configuration works for me.

You can also set additional environment variables: see [documentation](https://docs.astuto.io/deploy-docker/#2-edit-the-environment-variables-in-the-docker-compose-file). To understand what each env variable does, take a look at its corresponding [Rails documentation](https://guides.rubyonrails.org/configuring.html#config-action-mailer-smtp-settings). However, the configurations above should make it work without any additional work!

Please let me know if it works for you or not. If not, please set `EMAIL_RAISE_DELIVERY_ERRORS` to true and post the logged error.

If everything works fine for everyone, I'll update Astuto documentation to be more clear :)

**Comment by tgrignon** [comment]
I got this error

_web-1  | I, [2024-06-26T11:16:11.421772 #33]  INFO -- : [6026f39f-74ab-4d05-8665-347ff9282e8f] [https://url_with_my_email] [192.168.1.2] Completed 500 Internal Server Error in 110ms (ActiveRecord: 5.7ms | Allocations: 8718)
web-1  | F, [2024-06-26T11:16:11.422409 #33] FATAL -- : [6026f39f-74ab-4d05-8665-347ff9282e8f] [https://url_with_my_email] [192.168.1.2]
web-1  | [6026f39f-74ab-4d05-8665-347ff9282e8f] [https://url_with_my_email] [192.168.1.2] OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: wrong version number):
web-1  | [6026f39f-74ab-4d05-8665-347ff9282e8f] [https://url_with_my_email] [192.168.1.2]
web-1  | [6026f39f-74ab-4d05-8665-347ff9282e8f] [https://url_with_my_email] [192.168.1.2] app/controllers/registrations_controller.rb:25:in `send_set_password_instructions'_

It seems to relate to a SSL verification, but I don't need that, my internal server don't use it. I tried to put the variable to stop using it, without success.

 EMAIL_SMTP_OPENSSL_VERIFY_MODE: nil / none / false / what ever...

**Comment by riggraz** [comment]
Hi @tgrignon, I encountered that problem too and should be fixed with the latest main commit (24ef09c, 8 minutes ago). Otherwise, try to pass the environment variable `EMAIL_SMTP_TLS` set to false.

**Comment by tgrignon** [comment]
Now I got

Net::SMTPAuthenticationError (502 command not implemented

I tried with and without EMAIL_SMTP_TLS: false

      RAILS_LOG_TO_STDOUT: true
      EMAIL_RAISE_DELIVERY_ERRORS: true
      EMAIL_DELIVERY_METHOD: smtp
      EMAIL_SMTP_HOST: 192.168.1.2
      EMAIL_SMTP_PORT: 25
      EMAIL_SMTP_USER: ""
      EMAIL_SMTP_PASS: ""

**Comment by pilasguru** [comment]
A fresh docker image latest:

```
        "Id": "sha256:41eb321f6523172da60786be624708613844d1bf865ab2e33d3d3733df7d73b6",
        "RepoTags": [
            "riggraz/astuto:latest"
        ],
        "RepoDigests": [
            "riggraz/astuto@sha256:597cee6720b2468ce281997ecc9704f29ab69014e1b835dd0e4cf6632aed0198"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-06-26T11:19:26.454143179Z",
        "DockerVersion": "",
        "Author": "",
```

These env variables active:

```
# docker compose exec web env | grep EMAIL
EMAIL_SMTP_USER=
EMAIL_SMTP_TLS=false
EMAIL_MAIL_FROM=astuto@example.com
EMAIL_DELIVERY_METHOD=smtp
EMAIL_SMTP_HOST=smtp
EMAIL_SMTP_PORT=25
EMAIL_SMTP_PASS=
EMAIL_RAISE_DELIVERY_ERRORS=true
```

web (astuto) service do not show anything into stdout log, but smtp (postfix) service shows this:

```
smtp-1  | 2024-06-26T21:11:03.074773+00:00 878e13311e04 postfix/smtpd[141]: connect from astuto-web-1.astuto_astuto[192.168.16.4]
smtp-1  | 2024-06-26T21:11:03.077193+00:00 878e13311e04 postfix/smtpd[141]: lost connection after AUTH from astuto-web-1.astuto_astuto[192.168.16.4]
smtp-1  | 2024-06-26T21:11:03.077275+00:00 878e13311e04 postfix/smtpd[141]: disconnect from astuto-web-1.astuto_astuto[192.168.16.4] ehlo=1 auth=0/1 commands=1/2

**Comment by riggraz** [comment]
Are you running Astuto in development or production mode (i.e. are you building the image from source code or pulling it from DockerHub)?

@tgrignon it seems like your smtp server does not support the `PLAIN` authentication method. Try to pass environment variable `EMAIL_SMTP_AUTH` set to `login`. Also, are you sure that `192.168.1.2` is the address of the smtp server? Remember you're working in Docker containers so make sure to check whether it's reachable from within the Docker web container (try to attach to the container, ping that address and make sure port 25 is open).

 @pilasguru make sure to set `RAILS_LOG_TO_STDOUT` to `true` in order to see the logs. Rails should definitely log something. Is `smtp` a smtp server container you're running alongside astuto? Which docker image are you using for that?

**Comment by pilasguru** [comment]
This is my docker-compose.yaml:

```
services:

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: astuto
      POSTGRES_PASSWORD: astuto
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - astuto

  smtp:
    image: mwader/postfix-relay
    restart: unless-stopped
    environment:
      - POSTFIX_myhostname=astutorelay.example.com
      - POSTFIX_mydestination=localhost
      - POSTFIX_mynetworks=127.0.0.0/8 0.0.0.0/0 [::1]/128 [::]/0
      - POSTFIX_smtp_tls_security_level=may
      - POSTFIX_smtpd_tls_security_level=none
      - POSTFIX_relayhost=smtprelay.example.com:587
      - POSTFIX_smtp_sasl_auth_enable=yes
      - POSTFIX_smtp_sasl_password_maps=static:user@example.com:password
      - POSTFIX_smtp_sasl_security_options=noanonymous
      - POSTFIX_smtp_tls_security_level=encrypt
      - POSTFIX_header_size_limit=4096000
    networks:
      - astuto

  web:
    image: riggraz/astuto:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: astuto
      POSTGRES_PASSWORD: astuto
      BASE_URL: https://astuto.example.com
      SECRET_KEY_BASE: ED0DF5790C5F13CA6856AC53C33A66FD5F8E345351879CB7516236AE
      EMAIL_DELIVERY_METHOD: smtp
      EMAIL_MAIL_FROM: astuto@exemple.com
      EMAIL_RAISE_DELIVERY_ERRORS: true

      EMAIL_SMTP_HOST: smtp
      EMAIL_SMTP_PORT: 25
      EMAIL_SMTP_USER: ""
      EMAIL_SMTP_PASS: ""

      RAILS_LOG_TO_STDOUT: true

    networks:
      - astuto
    ports:
      - 3000:3000

networks:
  astuto:
```

and I have this output from web:

```
web-1   | I, [2024-07-02T14:18:25.489626 #33]  INFO -- : [03d9ed71-1636-4001-8573-cbb31afaf20b] [https://isard.rwy.pub/users/password] [167.60.172.132] Completed 500 Internal Server Error in 230ms (ActiveRecord: 16.5ms | Allocations: 9591)
web-1   | F, [2024-07-02T14:18:25.491166 #33] FATAL -- : [03d9ed71-1636-4001-8573-cbb31afaf20b] [https://isard.rwy.pub/users/password] [167.60.172.132]
web-1   | [03d9ed71-1636-4001-8573-cbb31afaf20b] [https://isard.rwy.pub/users/password] [167.60.172.132] Net::SMTPAuthenticationError (503 5.5.1 Error: authentication not enabled
```

and this output from smtp service:

```
smtp-1  | 2024-07-02T14:18:25.487095+00:00 4de0a3764083 postfix/smtpd[141]: connect from astuto-web-1.astuto_astuto[192.168.160.3]
smtp-1  | 2024-07-02T14:18:25.488103+00:00 4de0a3764083 postfix/smtpd[141]: lost connection after AUTH from astuto-web-1.astuto_astuto[192.168.160.3]
smtp-1  | 2024-07-02T14:18:25.488119+00:00 4de0a3764083 postfix/smtpd[141]: disconnect from astuto-web-1.astuto_astuto[192.168.160.3] ehlo=1 auth=0/1 commands=1/2
```
