### ISSUE TITLE
Self-hosted Astuto doesn't work when IP address is given for BASE_URL?

### ISSUE THREAD

**Issue by vbresan** [astuto/astuto#382]
I am testing Astuto on a VPS that currently has no domain assigned. I have followed the instructions and for BASE_URL I have entered the VPS IP address instead.

Astuto successfully starts with `sudo docker compose up` and the tail of the output is the following:
```
web-1  | * Listening on http://0.0.0.0:3000
web-1  | Use Ctrl-C to stop
```

The website is not available when I open the address given as the BASE_URL. No log messages are displayed when I try to connect. Am I missing something obvious?

**Comment by riggraz** [comment]
Hi vbresan!

Can you provide your docker-compose.yml configuration and additional info on your setup? Also, if you're running Astuto in production and encounter problems, you should set the environment variable `RAILS_LOG_TO_STDOUT` to true in order to see server logs.

**Comment by vbresan** [comment]
Here is my `docker-compose.yml`

```
version: '3.4'
services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_USER: <mypostgresusername>
      POSTGRES_PASSWORD: <mypostgrespassword>
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    image: riggraz/astuto:latest
    environment:
      POSTGRES_USER: <mypostgresusername>
      POSTGRES_PASSWORD: <mypostgrespassword>
      BASE_URL: http://<ip_address or 'localhost'>
      SECRET_KEY_BASE: <mysecretkeybase>
      RAILS_LOG_TO_STDOUT: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    
volumes:
  dbdata:
```

Please note that RAILS_LOG_TO_STDOUT is not mentioned in [environment variables](https://docs.astuto.io/deploy-docker/#2-edit-the-environment-variables-in-the-docker-compose-file) and I have not noticed any extra log output.

The output of `sudo docker compose up` is the following:

```
WARN[0000] /home/viktor_bresan/astuto/docker-compose.yml: `version` is obsolete 
[+] Running 2/2
 ✔ Container astuto-db-1   Created                                                                        0.0s 
 ✔ Container astuto-web-1  Recreated                                                                      0.2s 
Attaching to db-1, web-1
db-1   | 
db-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1   | 
db-1   | 2024-07-15 09:09:36.661 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-2.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db-1   | 2024-07-15 09:09:36.663 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1   | 2024-07-15 09:09:36.663 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1   | 2024-07-15 09:09:36.671 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1   | 2024-07-15 09:09:36.683 UTC [25] LOG:  database system was shut down at 2024-07-15 09:08:59 UTC
db-1   | 2024-07-15 09:09:36.700 UTC [1] LOG:  database system is ready to accept connections
web-1  | Preparing database...
web-1  | Current version: 20240708191938
web-1  | Current version: 20240708191938
web-1  | Database prepared.
web-1  | => Booting Puma
web-1  | => Rails 6.1.7.8 application starting in production 
web-1  | => Run `bin/rails server --help` for more startup options
web-1  | Puma starting in single mode...
web-1  | * Puma version: 5.6.8 (ruby 3.0.6-p216) ("Birdie's Version")
web-1  | *  Min threads: 5
web-1  | *  Max threads: 5
web-1  | *  Environment: production
web-1  | *          PID: 33
web-1  | * Listening on http://0.0.0.0:3000
web-1  | Use Ctrl-C to stop
```

Additional info on my setup: it's a clean VPS from Google (Compute Engine) running Ubuntu 24.04. 

As mentioned earlier, I can not connect to the website, not even from the shell trying to open http://localhost
There is no additional log output when I try to open the website.
